### ISSUE TITLE
Latest tag fails to start

### ISSUE THREAD

**Issue by gpavlidi** [appropriate/docker-postgis#10]
It fails with
```
/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgis.sh
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 55) running in data directory "/var/lib/postgresql/data"?
```

Rolling it back to a tag 10 days ago (22ed955cce18) works

**Comment by md5** [comment]
When did you pull the image? Also, how are you starting the container?

I made some updates today to deal with upstream changes in the Postgres image (cf #9). The image seemed to start up fine for me without the error you mention, but perhaps I missed something.

**Comment by gpavlidi** [comment]
Actually it seems like it's a bad build. I just forked your project and set an Automated build with your latest it works... It might worth it to rebuild it.
I ran the below and it fails
```
 docker run -d --name test_my_postgres -t mdillon/postgis
```
but below works
```
docker run -d --name test_my_postgres2 -t gpavlidi/docker-postgis
```

Repo is an identical fork, so maybe the automated build messed it up?

**Comment by md5** [comment]
I just pulled the latest build of the image and it worked fine. The latest build was actually started around the time I made my last comment, so it's possible that fixed things. I recall at one point a few months back that automated builds with triggers based on official images were not working correctly (due to the transition from the v1 to the v2 registry backend as I understand), but I'm not sure if that situation was every fully sorted out. I also know that there's a new beta version of the registry that's due to launch soon, so perhaps they've sorted out some of the automated build issues there.

For reference, here's the image I tested with, pulled from Docker Hub:

```console
$ docker images mdillon/postgis
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
mdillon/postgis     latest              6c99626c0700        52 minutes ago      431.7 MB
```

**Comment by md5** [comment]
Just to close the loop, it seems like you pulled a version of `mdillon/postgis` that was based on the updated `postgres` base image with changes from docker-library/postgres#75, but hadn't yet incorporated the changes from #9. This would mean that `postgres --single` was trying to run when a real Postgres instance was already running, leading to the error you encountered.

**Comment by gpavlidi** [comment]
wow... talking about luck!
I confirm that pulling mdillon/postgis:latest works fine now.
I guess my takeaway lesson is I ll start using tags, and leave :latest for the brave.

Thanks for looking into this.

**Comment by md5** [comment]
Using a tag other than `latest` wouldn't have made a difference. The numbered tags were all similarly affected.

The issue is that a breaking change was introduced into the `postgres` image by docker-library/postgres#75. I knew the changes were coming down and had the necessary adjustments for `mdillon/postgis` prepared, but I had to wait until the `postgres` changes were live to push my changes.

In retrospect, since I knew a change was coming, I should have turned off the [repository link](https://docs.docker.com/docker-hub/builds/#repository-links) that causes pushes of the `postgres` image to rebuild the `mdillon/postgis` image. This would have allowed me to control the timing better and avoid a period where the image was broken.

Sorry for the inconvenience!
