### ISSUE TITLE
Rebuild images on the docker hub

### ISSUE THREAD

**Issue by kurlzor** [appropriate/docker-postgis#53]
I thought the postgis images were rebuilt automatically when official postgres images are pushed but it seems like they're not. This [PR](https://github.com/docker-library/postgres/pull/255) was merged, new postgres images were pushed to the hub and it didn't trigger any build.
Would you mind triggering a build manually ? Thanks 🙂

**Comment by md5** [comment]
I recently moved the builds from Docker Hub to Docker Cloud since they were previously not building on push (due to a move from `md5/docker-postgis` to `appropriate/docker-postgis` back in 2015). I guess I neglected to deal with the "repository link" to the `postgres` image in the process.

Unfortunately, it look like Docker Cloud doesn't support repository links... I've gone back into the Docker Hub automated builds and re-enabled the repository link. This *should* mean that pushes to `master` trigger a build on Docker Cloud's automated build infrastructure and that changes to the `postgres` image will trigger a build on the (semi-deprecated, barely-supported) Docker Hub infrastructure.

I've also manually kicked off the image builds 😖
