### ISSUE TITLE
How to update underlying postgres

### ISSUE THREAD

**Issue by guybowden** [appropriate/docker-postgis#88]
Probably the wrong place to ask this - not sure where is the right place.

I'm using this image as part of a docker-compose setup. Last week Postgres [released](https://www.postgresql.org/docs/9.6/static/release-9-6-8.html) a security update that I'd like to apply.

How do I do this? I noticed that the underlying postgres image was updated last week, but have rebuilt my setup after a `docker purge` / complete reset via docker for mac. But the image isn't the latest one from last week.

am I doing anything wrong? is there a way to apply the upgrade directly to my container so that it works until the patch is applied?

**Comment by md5** [comment]
Have a look at the [`update-postgis.sh`](https://github.com/appropriate/docker-postgis/blob/master/update-postgis.sh) script. I haven't used it myself, but you should be able to use it to upgrade the extensions in an existing database. I would strongly suggest that you fully understand what the script it doing before running it.

There are some basic instructions for running the script here: https://github.com/appropriate/docker-postgis#known-issues--errors

If you want more information on how it's used, perhaps @lechup could help since they added the script in #54.
